Fix suika3-launcher

diff --git a/resources/freedesktop/suika3-launcher b/resources/freedesktop/suika3-launcher
--- a/resources/freedesktop/suika3-launcher
+++ b/resources/freedesktop/suika3-launcher
@@ -1,21 +1,89 @@
 #!/bin/sh
 
-LAUNCHER_DIR="";
-for base in /usr /usr/local /usr/pkg /opt /app; do
-    for sub in "share/suika3/launcher" \
-               "share/doc/suika3/launcher" \
-               "share/docs/suika3/launcher"; do
-        target="$base/$sub";
-        if [ -d "$target" ]; then
-            LAUNCHER_DIR="$target";
-            break 2;
-        fi
-    done
-done
+if [ -z "$1" ]; then
+    # If no option is specified, search the launcher directory,
+    # and then run the suika3 command. The launcher is implemented
+    # using Suika3 VM.
 
-if [ -z "$LAUNCHER_DIR" ]; then
-    echo "No launcher directory found.";
-    exit 1;
+    # Try searching for each prefix and for each subdirectory.
+    LAUNCHER_DIR="";
+    for base in /usr /usr/local /usr/pkg /opt /app; do
+        for sub in "share/suika3/launcher" \
+                   "share/doc/suika3/launcher" \
+                   "share/docs/suika3/launcher"; do
+            target="$base/$sub";
+            if [ -d "$target" ]; then
+                LAUNCHER_DIR="$target";
+                break 2;
+            fi
+        done
+    done;
+    if [ -z "$LAUNCHER_DIR" ]; then
+        echo "No launcher directory found.";
+        exit 1;
+    fi;
+
+    # Run the launcher by running Suika3 VM.
+    cd "$LAUNCHER_DIR";
+    exec suika3;
+else
+    # If there is an option, try opening the directory.
+    # When we don't have access rights to the directory,
+    # we assume we are in a Flatpak sandbox and
+    # try getting a portal.
+
+    # Get the directory.
+    DIR="$1";
+    if [ "$DIR" = "--open" ]; then
+        DIR="";
+    fi;
+
+    # If a file is specified, get the parent directory.
+    if [ -f "$DIR" ]; then
+        DIR=$(dirname "$DIR");
+    fi;
+
+    # If the assets are not accessible, use the file choose.
+    if [ ! -d "$DIR" ] || [ ! -r "$DIR/start.novel" ] || [ ! -r "$DIR/main.ray" ]; then
+        # Prepare a default directory for the file chooser for convinience.
+        DEFAULT_PATH="";
+        if [ -z "$DIR" ]; then
+            DEFAULT_PATH="";
+        else
+            DEFAULT_PATH="$DIR/";
+        fi;
+
+        # Call the file chooser to get a portal for a directory.
+        export GTK_USE_PORTAL=1;
+        DIR=$(zenity --title "Open a game folder containing main.ray" \
+                     --file-selection \
+                     --directory \
+                     --filename="$DEFAULT_PATH");
+        if [ -z "$DIR" ]; then
+            exit 1;
+        fi;
+    fi;
+
+    # Run the suika3 command.
+    if cd "$DIR"; then
+        # Remove a log if exists.
+        rm -f log.txt;
+
+        # Run.
+        suika3;
+
+        # Show a log if generated.
+        if [ -f log.txt ]; then
+            zenity --error \
+                   --title="Suika3 Engine" \
+                   --text="$(printf 'Error\n%s' "$(cat log.txt)")";
+            exit 1;
+        fi;
+    else
+        # Could not access the directory
+        zenity --error \
+               --title="Suika3 Engine" \
+               --text="Failed to access the directory:\n$DIR\n\nPlease check your Flatpak permission settings."
+        exit 1
+    fi;
 fi
-
-cd "$LAUNCHER_DIR" && suika3
